name: All tests on PR
on:
  pull_request:
    branches:
      - main
jobs:
  setup:
    uses: ./.github/workflows/run-all-setup.yml
  run:
    uses: ./.github/workflows/run-all-tests.yml
    secrets: inherit
