name: All Tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: make test
      - name: Run E2E Tests
        run: make test-e2e-debug
      - uses: actions/upload-artifact@v2
        if: ${{ failure() || success() }}
        with:
          name: Recordings
          path: test/e2e/lnd/e2e_videos/
