name: All tests on push to main
on:
  push:
    branches:
      - main
jobs:
  setup:
    uses: ./.github/workflows/run-all-setup.yml
  run:
    uses: ./.github/workflows/run-all-tests.yml
    secrets: inherit
