name: All Tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags')
    steps:
      - name: Run Tests
        uses: actions/checkout@v2
        run: make test
      - name: Run E2E Tests
        uses: actions/checkout@v2
        run: make test-e2e-debug
